project_id = "tkfotxeqwrfkxzjljcyv"

[functions.oracle-chat]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.send-broadcast-email]
verify_jwt = false